### ISSUE TITLE
Bug: Need attention immediately

### ISSUE THREAD

**Issue by giyegiywiyesihfsngcyuouawcvw** [RogueEdit/onlineRogueEditor#101]
im on windows
the thingy isnt wotking when i do 26 after i did 5

![image](https://github.com/RogueEdit/onlineRogueEditor/assets/105468016/223d809b-4168-40ba-a953-850dd5bad57d)

**Comment by JulianStiebler** [comment]
@Valsahn yeah that seeding wasnt smart. It actually makes not much difference, further version up dont have it.
https://github.com/RogueEdit/onlineRogueEditor/releases/tag/v0.2... :'D lets hope it stays. I think we are just conflicting with cloudflare.
