### ISSUE TITLE
Response 403 

### ISSUE THREAD

**Issue by DavisLy** [RogueEdit/onlineRogueEditor#102]
**What Operating System are you on** - Windows, Ubuntu, Mac, ...
- ... Windows

**Describe the bug** - A clear and concise description of what the bug is.
- ... I was trying to unlock everything using 17 but then when I got to saving the data it said response 403 - Forbidden. We have no authoriazion to access the resource. 

**To Reproduce** - Describe the steps needed to reproduce the bug.
- ... login then enter slot 1 then command 17 and entering 1 for all response last command 26

**Expected behavior** A clear and concise description of what you expected to happen.
- ... for it to work save to my account and I would load up a save a try it for the first time

**Screenshots** - If applicable, add screenshots to help explain your problem.
![image](https://github.com/RogueEdit/onlineRogueEditor/assets/116730012/9d0df042-47a3-4748-8fcb-850d09fc75a0)
![image](https://github.com/RogueEdit/onlineRogueEditor/assets/116730012/3a1eae76-9fe7-43c9-866d-f5d1c30f277e)
![image](https://github.com/RogueEdit/onlineRogueEditor/assets/116730012/7d222430-46f6-4c8e-9a43-9f1f35a49ac2)
![image](https://github.com/RogueEdit/onlineRogueEditor/assets/116730012/40e49cc0-fccc-40b0-abdd-cbc095d8fc7b)

**Comment by giyegiywiyesihfsngcyuouawcvw** [comment]
BRO I HAD THE SAME THING WITH 5 
![image](https://github.com/RogueEdit/onlineRogueEditor/assets/105468016/88fa4ad3-a994-45e1-93d9-679d871fc9a4)

**Comment by JulianStiebler** [comment]
Yeah they are blocking some of our headers. probably reading github. :D

**Comment by JulianStiebler** [comment]
Im on it tho some last trys

**Comment by DavisLy** [comment]
OK, can you respond to this message again once you finish that?

**Comment by D0ctorLeon** [comment]
> Im on it tho some last trys

Is there a new discord link ? The old one is down

**Comment by JulianStiebler** [comment]
@DavisLy sure

https://github.com/RogueEdit/onlineRogueEditor/releases/tag/v0.2... :'D lets hope it stays. I think we are just conflicting with cloudflare. I added some more stable header logic and a better generator

@D0ctorLeon Nah still active

**Comment by KyoKaguya** [comment]
I still got the problem even in the new version
