### ISSUE TITLE
error 403 in version 1.2 rip T_T

### ISSUE THREAD

**Issue by nichan200** [RogueEdit/onlineRogueEditor#103]
well it was fun while it lasted now to wait for it to be solved version 1.2 fell in the end you can no longer save in this version either

![pokerogue error5](https://github.com/RogueEdit/onlineRogueEditor/assets/15617682/49038260-7eec-4a7c-bf9c-2864f40031cb)

rest in peace 1.2

**Comment by JulianStiebler** [comment]
https://github.com/RogueEdit/onlineRogueEditor/releases/tag/v0.2... :'D lets hope it stays. I think we are just conflicting with cloudflare. I added some more stable header logic and a better generator
