### ISSUE TITLE
Bug: Need attention immediately

### ISSUE THREAD

**Issue by Reizen82** [RogueEdit/onlineRogueEditor#106]
![image](https://github.com/RogueEdit/onlineRogueEditor/assets/93852241/50644cdb-c8b0-4696-a900-0c7e15e462bb)

Not sure what this means but was trying to edit 1 starter and kept getting this error

**Comment by JulianStiebler** [comment]
You used the newest V0.2?

403 means they banned access headers from that version. Either them or cloudflare

**Comment by Reizen82** [comment]
Newest version from what was posted. Was working for a bit but now doesnt

**Comment by JulianStiebler** [comment]
Yeah they patched the endpoints. See on theyre rogueserver repo for more info
now its giving 404's
