### ISSUE TITLE
Bug: 404 error

### ISSUE THREAD

**Issue by akie7297** [RogueEdit/onlineRogueEditor#110]
**What Operating System are you on** - Windows, Ubuntu, Mac, ...
- Windows10

**Describe the bug** - A clear and concise description of what the bug is.
-404 error occurs while executing code, entering ID, and retrieving information.

**To Reproduce** - Describe the steps needed to reproduce the bug.
- I'm playing in Korean version
If you enter your ID after executing the code, 404 error appears
Error in function .__load_data(): [Errno 2] No such file or directory: 'trainer.json' will be printed o

**Expected behavior** A clear and concise description of what you expected to happen.
- I don'n know

**Screenshots** - 
<img width="721" alt="화면 캡처 2024-06-08 085735" src="https://github.com/RogueEdit/onlineRogueEditor/assets/130016870/32fa316c-d9ae-459a-a91e-c3553bc0a798">
ut

**Comment by JulianStiebler** [comment]
404 means target not found. They changed the endpoints and we have to decide how to move on.

**Comment by akie7297** [comment]
that mean Are you saying that it's impossible to operate now?

I'll be waiting for an update.
