### ISSUE TITLE
404 and 403 error help

### ISSUE THREAD

**Issue by CrystalGemHeliotrope** [RogueEdit/onlineRogueEditor#111]
![Screenshot 2024-06-07 180247](https://github.com/RogueEdit/onlineRogueEditor/assets/101293576/aaff4475-b200-4a24-99ab-b51612f30f70)
I am having some issues trying to log in. Did I do something wrong? do I need to redownload? make a new folder? Help? v0.2?

**Comment by CrystalGemHeliotrope** [comment]
like I do realize you are aware of it, but it is just like...I feel like Im missing something here

**Comment by JacksonDutton** [comment]
1: Using requests.
2: Using own browser. Use when 1 doesnt work.
Please choose a method of logging in: 1
Username: jacksond7
Password (password is hidden):
Adding delay to appear more natural to the server.
------------------------------
Login successful.
HTTP Status Code: 200
Response URL: https://api.pokerogue.net/account/login
Response Headers: {'Date': 'Sat, 08 Jun 2024 01:22:16 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Access-Control-Allow-Headers': 'Authorization, Content-Type', 'Access-Control-Allow-Methods': 'OPTIONS, GET, POST', 'Access-Control-Allow-Origin': 'https://pokerogue.net', 'X-Pokemon': 'jirachi', 'CF-Cache-Status': 'DYNAMIC', 'NEL': '{"success_fraction":0,"report_to":"cf-nel","max_age":604800}', 'Server': 'cloudflare', 'CF-RAY': '890511e20a47b441-HKG', 'Content-Encoding': 'br', 'alt-svc': 'h3=":443"; ma=86400'}
------------------------------
Logged in as: Jacksond7
{'authorization': 'FnT6uk1RPpTnHqRejXq1tXdsYer0nsI7yu8Qzp9arc8=', 'Accept': 'application/json', 'Content-Type': 'application/json', 'Accept-Language': 'it-IT,it;q=0.8,en-US;q=0.5,en;q=0.3', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Connection': 'keep-alive', 'Origin': 'https://pokerogue.net', 'Referer': 'https://pokerogue.net/', 'Sec-Ch-Ua': '"Google Chrome";v="112", "Chromium";v="112", "Not.A/Brand";v="24"', 'Sec-Ch-Ua-Mobile': '?0', 'Sec-Ch-Ua-Platform': '"Macintosh"', 'Sec-Fetch-Dest': 'empty', 'Sec-Fetch-Mode': 'cors', 'Sec-Fetch-Site': 'same-site', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36'}
Enter slot (1-5): 1
Fetching trainer data...
Error fetching trainer data. Please restart the tool.
 404 Client Error: Not Found for url: https://api.pokerogue.net/savedata/get?datatype=0
Sleeping 3 seconds to look more human before fetching saveslot-data.
Fetching data for Slot 1...
Error fetching save-slot data. Please restart the tool.
 404 Client Error: Not Found for url: https://api.pokerogue.net/savedata/get?datatype=1&slot=0
 
 
I've got the same issue - tried logging in with both 1 and 2 options..

**Comment by Rainson1** [comment]
Same here

**Comment by FaultyDev** [comment]
Im having this same issue too, anyone know a fix for it?

**Comment by oterew** [comment]
can we just have a update or a new patch thats works

**Comment by Reizen82** [comment]
Be patient there is no fix currently the devs are figuring out how they want to proceed.

**Comment by JulianStiebler** [comment]
@oterew get off our github. we work hard and have a life too, if you have no eyes and cant see the devs patched it in the night xD some ppl are so dumb and thankless its insane
