### ISSUE TITLE
Error fetching save-slot data. Please restart the tool.  404 Client Error: Not Found for url: https://api.pokerogue.net/savedata/get?datatype=1&slot=0

### ISSUE THREAD

**Issue by cascadia123** [RogueEdit/onlineRogueEditor#112]
**What Operating System are you on** - Windows, Ubuntu, Mac, ...
- ...
windows
**Describe the bug** - A clear and concise description of what the bug is.
- ...404 cannot be fetched
- 404 Client Error: Not Found for url: https://api.pokerogue.net/savedata/get?datatype=1&slot=0

**To Reproduce** - Describe the steps needed to reproduce the bug.
- ... - 

**Expected behavior** A clear and concise description of what you expected to happen.
- ... It asked me to restart but still not working 
![1231415](https://github.com/RogueEdit/onlineRogueEditor/assets/172114151/56296c17-4de1-40b5-9ed3-d93fced25ef5)

**Screenshots** - If applicable, add screenshots to help explain your problem.

**Comment by JulianStiebler** [comment]
This is known... Theres another issue already open about 403 and 404s. The devs changed the endpoints and stuff so not sure whats in the future
