### ISSUE TITLE
Bug: Need attention immediately

### ISSUE THREAD

**Issue by 2no-0904** [RogueEdit/onlineRogueEditor#115]
**What Operating System are you on** - Windows, Ubuntu, Mac, ...
- Windows 
- Python
- v0.2.1 (https://github.com/RogueEdit/onlineRogueEditor/releases) 
 
**Describe the bug** - A clear and concise description of what the bug is.
- 403 Error Output When Saved

**To Reproduce** - Describe the steps needed to reproduce the bug.
- 26 (save data upload)

**Expected behavior** A clear and concise description of what you expected to happen.
- An error is output when attempting to save.

**Screenshots** - If applicable, add screenshots to help explain your problem.

![403 saved error](https://github.com/RogueEdit/onlineRogueEditor/assets/172138690/ad42077e-8207-4900-8dff-54c57ee54d76)

**Comment by dylanjenks** [comment]
I am also having this bug. Cant actually upload my save, so the editor is effectively broken right now.

**Comment by JulianStiebler** [comment]
Reading the readme.md's helps :)
