### ISSUE TITLE
Bug: v0.2.2 Login issues with no authoriazion to access the resource + same issue last post

### ISSUE THREAD

**Issue by Nico23422** [RogueEdit/onlineRogueEditor#121]
What Operating System are you on 
Windows
Describe the bug - A clear and concise description of the bug.
i can't log in using 1 gives "We have no authorization to access the resource"
open cmd, navigate to the src folder, run python main.py
login using "1"
error happened
We have no authorization to access the resource
only when typing in 1 when login, not 2

saving is the same with the We have no authorization to access the resource. Please report to our GitHub.
Expected behavior A clear and concise description of what you expected to happen.

The script will save my edited local file
Screenshots - If applicable, add screenshots to help explain your problem.
![bug2](https://github.com/RogueEdit/onlineRogueEditor/assets/24641004/e8c85bdc-b4a7-4fc7-ace3-decdf053ceef)

**Comment by JulianStiebler** [comment]
Its big and fat on the readme "Not Working, do not use"

**Comment by Nico23422** [comment]
> Its big and fat on the readme "Not Working, do not use" Also removed ur screenshot, there was ur account name

this was before you updated it to say that
and the screenshot i didn't get to change it since i was sleeping but thanks for reemovinf it
