### ISSUE TITLE
compiled file is gone?

### ISSUE THREAD

**Issue by HeavenlyBeggar** [RogueEdit/onlineRogueEditor#123]
Hey,

This might be a dumb question, but it seems like the compiled folder is gone, how do we start the program now?

**Comment by Mastershuckle** [comment]
The homepage states that it's broken right now and they're currently trying to fix it so they remove the compiler until they fix the issue

**Comment by HeavenlyBeggar** [comment]
i see, thanks for helping me out!
Thank you for answering so fast :)

**Comment by JulianStiebler** [comment]
Reading the readme.md's can help a lot ^^
