### ISSUE TITLE
Question: Fire orb doesn't work

### ISSUE THREAD

**Issue by EtronieDENG** [RogueEdit/onlineRogueEditor#196]
Hi!
I notice that the item should be flame_orb but not fire orb

![image](https://github.com/user-attachments/assets/5331ff9e-e1d8-4ecb-bcc8-aa2d503749fb)

![image](https://github.com/user-attachments/assets/4eb3cb84-6c2b-4409-b65c-f00c3d2de0b0)

**Comment by JulianStiebler** [comment]
Ah right; my bad. You can change it in `modules/itemLogic.py` for yourself; i won't push a update or commit unless i find a trustworthy new maintainer.
