### ISSUE TITLE
Feature: Reduce Starters Cost or Increase Points Limit

### ISSUE THREAD

**Issue by mour0** [RogueEdit/onlineRogueEditor#49]
**Is your feature request related to a problem? Please describe.**
When starting a new game, the user is currently limited to a maximum of 10 (classic) or 15 (endless) points. This restriction prevents users from selecting any combination of starters they desire.

**Describe the solution you'd like to see implemented**
Either increase the limit or reduce the cost of every starter.

**Comment by JulianStiebler** [comment]
![starter](https://github.com/RogueEdit/onlineRogueEditor/assets/68881884/16b2fede-bb50-4c06-8f35-ae81ddbed6da)

Is already reduced but not exposed to user input

same as PR #50 

Should we add them as user inputs? @claudiunderthehood 

-> Cost Reduction
-> passiveAttr
