### ISSUE TITLE
Question: Attention needed

### ISSUE THREAD

**Issue by funnygun555** [RogueEdit/onlineRogueEditor#60]
idk if this is a dumb question or not as i could just be doing something wrong but every time i put i my credentials it says "Login failed with requests: 500 Server Error: Internal Server Error for url: https://api.pokerogue.net/account/login" I am putting i the write credentials so idk if 
this is a issue o my part or not

**Comment by JulianStiebler** [comment]
You made sure you have the current version? Yesterday was a pre-release and could have had some problems.
Are you on windows? Worst case just run the code from source and check if it solves the problem.

If it still doesnt work you always can use V0.1.2 - it has the old login logic but other than not much missing features.

**Comment by funnygun555** [comment]
> You made sure you have the current version? Yesterday was a pre-release and could have had some problems. Are you on windows? Worst case just run the code from source and check if it solves the problem.
> 
> If it still doesnt work you always can use V0.1.2 - it has the old login logic but other than not much missing features.

hey i used the source code and it worked great thanks

**Comment by JulianStiebler** [comment]
Perfect :) Yeah sometimes it can't handle the brotli encoded server response correctly depending on some systems i am not sure what causes that but running from source ensurers you have all packages and so it did work as you explained :)
