### ISSUE TITLE
It might just be my lack of computer knowledge ,but when I try and use a command to run the code "sh". I get an error. Any ideas?

### ISSUE THREAD

**Issue by TheDarkPinecone** [RogueEdit/onlineRogueEditor#67]
<img width="918" alt="Screenshot 2024-06-03 at 11 33 29 PM" src="https://github.com/RogueEdit/onlineRogueEditor/assets/152344405/b85f3314-27db-4947-ab3b-5c9dabb0c188">

**Comment by JulianStiebler** [comment]
If you are on a Mac Intel;
If its set as non-executable:
`sh [pyRogue-version].sh`

Otherwise try
`chmod +x  [pyRogue-version].sh`
`./[pyRogue-version].sh`

Otherwise need to await response from @claudiunderthehood he has a mac and more clue

**Comment by JulianStiebler** [comment]
Looking as a stall issue, closing
