### ISSUE TITLE
Login Failed in Edit Program

### ISSUE THREAD

**Issue by kk1334** [RogueEdit/onlineRogueEditor#77]
**A clear and concise description of what the question is.**
Hi, I'm really enjoying the program you made. Thank you
But I can't login to the program at the moment, so I'm going to ask you a question
I don't know why it was rejected after using it well

I modified the starter
When I changed Pokemon to shiny, it was Luck 3 but the color of Luck 3 didn't come out
I changed it to Luck 1 and sent the data to pokerogue.net sever
After that, I tried to check if it went well, but I got an error if I sent the data in the lobby of the new game, and I don't think I saved the data, so I tried to try again later, but the program couldn't login

If you look at the log

[Login failed. 403 Client Error: Forbidden for url: https://api.pokerogue.net/account/login
Wrong credentials.]

That's what it says

I login well on pokerogue.net and I have no problem playing games, but I only want to edit the Pokemon I want

Ps. Even if you try to create a new account, your program does not login the same way
Is it an IP problem?

Ps2. For your information, I am not a native of English-speaking culture, but I asked the question through the translator, so I hope you understand even if the sentence is weird

**Additional contents 
0.1.4V can be login, but data cannot be send data on the server (No. 26) 
writing at  19:30PM Korean time**  (UTC+9:00)
------

**Comment by Velocity942** [comment]
Same error and using latest version

**Comment by TIANAONG** [comment]
same here it been Login failed. 403 for 30 min

**Comment by lebaes** [comment]
same here

**Comment by GeoX333** [comment]
Also receiving log in error

**Comment by ZotoBro** [comment]
I have the same issue, using latest version as well. Accessing https://api.pokerogue.net/account/login manually in-browser also gets blocked by CloudFlare but i'm not sure if that was possible before or if that has been blocked

**Comment by JulianStiebler** [comment]
Hotfixed version avaible, will deploy a more reliable way to supply "dynamic data" later that day

**Comment by JulianStiebler** [comment]
Adding a new class

```
class HeaderGenerator:
    """
    A class to generate randomized but valid HTTP headers with User-Agent strings.

    This class maintains lists of different components used to construct User-Agent strings and headers. 
    It also handles the retrieval and caching of header data from a remote source.

    Class Attributes:
        file_path (str): Path to the local file storing header data.
        file_path_public (str): Path to the public file storing header data.
        git_url (str): URL to fetch header data from a remote source.
        headers (str): Header data read from a local file or fetched from the remote source.
    """
```

This should allow for solving those errors easier.
