### ISSUE TITLE
Question: Attention needed

### ISSUE THREAD

**Issue by Ashukyo** [RogueEdit/onlineRogueEditor#80]
**A clear and concise description of what the question is.**
- I tried logging into the editor but it wouldn't let me. It keeps saying login failed. 403 Client error: forbidden for url : https://api.pokerogue.net/account/login . I tried 3 different accounts to see if it worked and nothing. Do you know how I could fix this by chance?

**Comment by JulianStiebler** [comment]
You tryed the hotfixed version? V0.1.6

**Comment by Thizzle715** [comment]
> You tryed the hotfixed version? V0.1.6

Just gonna reply for them rq, The hotfixed version is having the same issue at the moment. It really is a game of cat and mouse.

**Comment by Thizzle715** [comment]
![image_2024-06-06_053950258](https://github.com/RogueEdit/onlineRogueEditor/assets/171864532/a2259c0b-7221-4b26-8769-b31ef75a0ef3)

**Comment by DivineDiamond** [comment]
im having the same issue. is it cool if i just leave this here to be notified when theres a fix?

**Comment by caprino12** [comment]
i have the same problem

**Comment by Ashukyo** [comment]
> You tryed the hotfixed version? V0.1.6

I just did, it works thank you very much. Didn't see the hotfix earlier.

**Comment by JulianStiebler** [comment]
Yeah we are trying to get another fix but ...^^

**Comment by JulianStiebler** [comment]
v0.1.2 works with the old login logic

**Comment by Reizen82** [comment]
![image](https://github.com/RogueEdit/onlineRogueEditor/assets/93852241/87444ea0-c599-42a7-a40d-47ea495f8874)
Seems to be getting this when it tries to save to the server

**Comment by SummerBreezze** [comment]
> Yeah we are trying to get another fix but ...^^

how long would it take?

**Comment by JulianStiebler** [comment]
@Reizen82 500 is always a server error, wait a bit it resolves itself

and so far every version is working again. Its just that they ban the header information if its too often used and we have soo many users its hard to keep on top^^

**Comment by JulianStiebler** [comment]
v0.1.5
v0.1.6 

are working for me currently again, use as long as the headers are free to live :'D

To explain; we need access information to imitate browsers to be able to get a response from the server, and they "ban" those access information due to many users on the same access information. -so dumb xD
