### ISSUE TITLE
Bug: Need attention immediately

### ISSUE THREAD

**Issue by ItzDevNova** [RogueEdit/onlineRogueEditor#82]
**What Operating System are you on** - Windows, Ubuntu, Mac, ...
- Windows

**Describe the bug** - A clear and concise description of what the bug is.
- "Login failed. 403 Client Error: Forbidden for url: https://api.pokerogue.net/account/login" Even though my account works on pokerogue. I've tried on the hotfix and still doesn't work.

**To Reproduce** - Describe the steps needed to reproduce the bug.
- Every time I try to enter my account information

**Expected behavior** A clear and concise description of what you expected to happen.
- Bring up the typical menu

**Screenshots** - If applicable, add screenshots to help explain your problem.

![2e7346ef9abf7a619eb6054137643951](https://github.com/RogueEdit/onlineRogueEditor/assets/73325432/777aaeef-df42-49fb-b710-c02d8299b4b6)

**Comment by JulianStiebler** [comment]
Theres another issue open, im already on it.
