### ISSUE TITLE
Nature doesn't unlock issue

### ISSUE THREAD

**Issue by SoulFla** [RogueEdit/onlineRogueEditor#83]
**What Operating System are you on** - Windows, Ubuntu, Mac, ...
- Windows

**Describe the bug** - A clear and concise description of what the bug is.
- When I use 3 or 4 to unlock starter, it doesn't work unlock nature.
- 
![image](https://github.com/RogueEdit/onlineRogueEditor/assets/171940951/b62307a8-7e18-43d9-9d95-50b51c8ed81c)

All pokemon's nature fixed with Hardy

Please check for this, and thanks for your effort! :)

**Comment by JulianStiebler** [comment]
Solved in this release

**Comment by SoulFla** [comment]
> Solved in this release

It doesn't work for me ;)
