### ISSUE TITLE
Error unkock all starter Bug: Need attention immediately

### ISSUE THREAD

**Issue by nichan200** [RogueEdit/onlineRogueEditor#84]
I tried to reduce the cost of all the starters in the unlock all starters option and I got this error

![IMG_20240606_100406](https://github.com/RogueEdit/onlineRogueEditor/assets/15617682/a2de1c51-4203-4d41-b1cf-f288f0758674)

**Comment by JulianStiebler** [comment]
Try to use a version earlier, we had a typo in that one, fixed in next version 👍

**Comment by JulianStiebler** [comment]
Staged to be fixed this realease in a minute
