### ISSUE TITLE
Bug: Need attention 

### ISSUE THREAD

**Issue by Badkat12** [RogueEdit/onlineRogueEditor#88]
**What Operating System are you on** - Windows, Ubuntu, Mac, ...
Windows
**Describe the bug** - A clear and concise description of what the bug is.
On version 0.1.2, an attempt to edit starters on the first save slot made the save unusable. The save cannot be overwritten, it cannot be manually opened, and pressing "continue" on the main screen gives the error "Your session data could not be loaded. It may be corrupted."
**To Reproduce** - Describe the steps needed to reproduce the bug.
Opening the first save slot (which had data at the time), and editing one of my starters (Nacli) produced the issue. The change to the starter was successful.
**Expected behavior** A clear and concise description of what you expected to happen.
Expected behavior was the change in the starter without making the save unusable.
**Screenshots** - If applicable, add screenshots to help explain your problem.
![Screenshot 2024-06-06 113436](https://github.com/RogueEdit/onlineRogueEditor/assets/171973506/994baedc-5fe0-4a29-b317-255bbcb89260)
![Screenshot 2024-06-06 113515](https://github.com/RogueEdit/onlineRogueEditor/assets/171973506/f37167a1-6005-4c56-9fbf-344db28c72f9)

Ideally, if there is a way to remove the save from the slot so I am not stuck with a corrupted save that would be appreciated. Not too worried about recovering the save itself. Thank you!

**Comment by JulianStiebler** [comment]
You can just clear out the slot_{} json and it should be an empty slot again
make it empty so its just {} inside

No idea why that happened tho, but it doesnt persist as bug in newer versions

**Comment by JulianStiebler** [comment]
We implemented now a version that makes the browser login always work in version0.1.8. Its in building, then this is also fixed in general that doesnt happen anymore
