### ISSUE TITLE
option 2 problem

### ISSUE THREAD

**Issue by nichan200** [RogueEdit/onlineRogueEditor#92]
I try in version 1.8 to enter with option 2 and it waits about 1 minute waiting for the login after logging in and from there the last thing comes to mind, I share 2 images of the problem,
![pokerogue error](https://github.com/RogueEdit/onlineRogueEditor/assets/15617682/a95ed393-5ae0-43bf-acbb-69e99b23ab58)
![pokerogue error2](https://github.com/RogueEdit/onlineRogueEditor/assets/15617682/caae845c-103e-4456-868b-860cccc1ac12)

**Comment by JulianStiebler** [comment]
Already working on 1.9 :'D That has working option 1. But ill  try to take care of that aswell, tyvm

At me it didnt happen sry /:

**Comment by nichan200** [comment]
no problem brother don't worry and thanks for your great work

**Comment by JulianStiebler** [comment]
ITs currently not possible to save anyway They added some more protection and we are on it. but its alrdy late so...^^

**Comment by JulianStiebler** [comment]
This one is fixed but saving is still meeh, can use version 0.1.2 aslong as they dont take that access headers down aswell
