### ISSUE TITLE
Question: Attention needed

### ISSUE THREAD

**Issue by khankim99** [RogueEdit/onlineRogueEditor#93]
**A clear and concise description of what the question is.**
- ...After completing editing, I try to upload, but an error occurs. I don't know why.
![f](https://github.com/RogueEdit/onlineRogueEditor/assets/171990214/164d014c-29a0-4eaf-a56e-2d8e5109b031)

**Comment by JulianStiebler** [comment]
Working on it

**Comment by khankim99** [comment]
it's okay bro! i use 0.1.2 ver now i can wait more!

**Comment by khankim99** [comment]
Will we be able to add additional Pokémon traits? Your fears and temper will be added

**Comment by JulianStiebler** [comment]
We know of that but its currently not possible to save anyway. They added some more protection and we are on it.

v0.1.2 should not be able to save either tho

**Comment by khankim99** [comment]
Saving is possible in v0.1.2. Why doesn't the other version work?

**Comment by JulianStiebler** [comment]
Its using another endpoint not exposed for our option1. Ill give it a shot and try it since we can use that endpoint as we did in v0.1.2 - good find tyvm
