### ISSUE TITLE
Question: Attention needed

### ISSUE THREAD

**Issue by Jo-NH** [RogueEdit/onlineRogueEditor#95]
hello sir. I used number 2 but it doesn't work like this
![캡처](https://github.com/RogueEdit/onlineRogueEditor/assets/171997419/3deccc14-276e-4cc6-9071-ab5ade470244)

**Comment by JulianStiebler** [comment]
We know of that but its currently not possible to save anyway. They added some more protection and we are on it.

**Comment by Jo-NH** [comment]
Is there no version that works..?

**Comment by JulianStiebler** [comment]
..? sounds like "Huh.. no working version?" well they just added security.

Your error tho is fixed in this testbuild avaiable https://github.com/RogueEdit/onlineRogueEditor/releases/tag/v0.1.8-testbuild7 but saving data seems to not work due to new security.
