### ISSUE TITLE
Bug: Option 2 bug

### ISSUE THREAD

**Issue by akie7297** [RogueEdit/onlineRogueEditor#96]
**What Operating System are you on** - Windows, Ubuntu, Mac, ...
- windows

**Describe the bug** - A clear and concise description of what the bug is.
-
If you enter and run ID information after selecting option 2, you can still wait for login data... After 1 to 2 minutes
Session ID: None
Token: None
Request Headers: null
These values are output

The language I use is Korean, but I wonder if I can't find it or if there is a solution because the Korean system is different.

For option 1, a 403 error appears.

<img width="770" alt="화면 캡처 2024-06-07 105051" src="https://github.com/RogueEdit/onlineRogueEditor/assets/130016870/8b1c7c22-3977-41eb-9362-07ef92f5954f">

**Comment by akie7297** [comment]
I use the Korean version.

I'm using Windows 10.

**Comment by JulianStiebler** [comment]
We know of that but its currently not possible to save anyway. They added some more protection and we are on it.

**Comment by akie7297** [comment]
omg Can I look forward to the next version?

**Comment by JulianStiebler** [comment]
Im on it :) But lets see what they did they first... it seems weird without code changes to theyre open source base to just stop working to save. I was just abut to push a fix for another bug but... 🔢

**Comment by JulianStiebler** [comment]
Atleast that error is fixed
