### ISSUE TITLE
Question: Attention needed

### ISSUE THREAD

**Issue by oterew** [RogueEdit/onlineRogueEditor#98]
I have a problem whenever I try and save it says I saved it Then I open my game up and its not changed

**Comment by oterew** [comment]
Error updating trainer data. Please restart the tool.
 403 Client Error: Forbidden for url: https://api.pokerogue.net/savedata/update?datatype=1&slot=0&trainerId=4787&secretId=29473
this is the error thats pops up

**Comment by JulianStiebler** [comment]
Ty for reporting but theres multiple issues already open..
