### ISSUE TITLE
IF YOU ENCOUNTER 503 PLEASE READ THIS

### ISSUE THREAD

**Issue by JulianStiebler** [RogueEdit/onlineRogueEditor#99]
We know about this problem. We are also working on it but it seems not in our hands. They patched theyre endpoints and they can change anything anytime. They definetly know and we just do it for education.
---
Be patient and stand by as we figure how to go forward.

**Comment by nichan200** [comment]
In fact, I tried it, it accesses both options well when logging in but it does not save the changes in both options of the 1.8 test version

**Comment by nichan200** [comment]
It's already solved for now, I tried 1.9 and both option 1 and 2 work. Thank you to the entire team for being there and for their hard work with the tool these last few days. I appreciate it with all my heart.

**Comment by JulianStiebler** [comment]
Please keep this clean so ppl can hopefully see it.
